### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by DSergioD** [pascal20997/pr_googlecse#2]
Pagination has only the previous and next page, whether it is possible to have potential page numbers ?

Tnx.

**Comment by pascal20997** [comment]
Hey Srdjan thanks for your request. It is possible to implement a pagination like google has:
![image](https://user-images.githubusercontent.com/1337769/136450476-a98c9d8c-23ab-417a-9c2c-1ac73ba1384a.png)

Keep in mind that the API provides just an estimated amount of pages so if some results have less than e.g. 10 Pages it can defer if you click on "page 2".

I will implement such a feature in the upcoming version that is compatible with TYPO3 v11 too.
